# Generated by Django 5.1.1 on 2024-09-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
