# Generated by Django 5.1.1 on 2024-09-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.CharField(max_length=100)),
                ('timing', models.CharField(max_length=100)),
                ('group_activities', models.BooleanField(default=False)),
                ('personal_training', models.BooleanField(default=False)),
                ('diet_counselling', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('yoga', models.BooleanField(default=False)),
                ('female_plan', models.BooleanField(default=False)),
                ('supplements', models.CharField(max_length=50)),
                ('others', models.CharField(max_length=100)),
                ('available_equipments', models.TextField()),
            ],
        ),
    ]
