# Generated by Django 5.1.1 on 2024-09-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
