# Generated by Django 5.1.1 on 2024-09-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_registration_image_alter_trainer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='image',
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
